[api]
timeout = 30
lsci_base_url = "https://unctadstat.unctad.org/datacentre/dataviewer/US.LSCI"



[data]
output_dir = "data"
input_dir = "doc"

years = [2019, 2020, 2021, 2022, 2023]
include_regions = ["Asia", "Europe", "Africa", "Americas"]

[ontology]
object_types = ["Economy", "LSCI_Measurement", "Time_Period", "Geographic_Region"]
link_types = ["MEASURED_BY", "RECORDED_IN", "BELONGS_TO", "CONNECTED_TO"]

[logging]
level = "INFO"
logfile = "logs/pipeline.log"
