[api]
timeout = 30
lsci_base_url = "https://unctadstat.unctad.org/datacentre/dataviewer/US.LSCI"
client_id = "4cb92f26-163f-48c5-a1dd-178500515966"
api_key = "otZtJQeE4c/CY5YK9ipVzDASOL1Ily7+P1pmCQJ8S/g="


[data]
output_dir = "data"
input_dir = "doc"

years = [2019, 2020, 2021, 2022, 2023]
include_regions = ["Asia", "Europe", "Africa", "Americas"]

[ontology]
object_types = ["Economy", "LSCI_Measurement", "Time_Period", "Geographic_Region"]
link_types = ["MEASURED_BY", "RECORDED_IN", "BELONGS_TO", "CONNECTED_TO"]

[logging]
level = "INFO"
logfile = "logs/pipeline.log"
